### ISSUE TITLE
Cram (FlashcardExchange) search by user is broken

### ISSUE THREAD

**Issue by helloworld1** [helloworld1/AnyMemo#309]
Original [issue 302](https://code.google.com/p/anymemo/issues/detail?id=302) created by helloworld1 on 2014-02-07T02:14:43.000Z:

The Cram V1 API is quite unstable. I need to update to V2 API in order to restore the Cram's function.

**Comment by StaticNoiseLog** [comment]
May I ask why this issue was closed?
Neither "Search by title" nor "Search by user" works for me with cram.com using build 155 (java.io.IOException).
Cram as a source for flashcards is really important for me. I hope it can be fixed.

**Comment by helloworld1** [comment]
Cram support is dropped in the latest version since the company behind cram stops supporting the Cram API.

Here is the email

API Developers-

Today we are announcing that Cram.com will end our Developer Program on May 1, 2015. Over the past several years, we’ve seen a proliferation of exciting applications from our developer community, and we’ve been thrilled to help the spread of flashcard creation products. We are now turning our focus to serving the needs of our student users on Cram.com and the Cram mobile applications. 

As of May 1, 2015, we will completely turn off our Version 1.0 and Version 2.0 API and longer longer support any API endpoints, including:

Create and upload flashcards
Search of the Cram.com content library
Download decks from the Cram.com library

You can visit the Cram.com terms of service here and our API documents here. 

If you have any questions, you can email our Engineering team at support[at]cram.com.

Thanks,

The Cram Engineering Team

**Comment by StaticNoiseLog** [comment]
What a shame that Cram.com stopped support for external clients!
AnyMemo is much better than their Android client.
I will write them a complaint, but their e-mail does not leave much room for hope.
