### ISSUE TITLE
"Conversion failed"

### ISSUE THREAD

**Issue by serheygmailcom** [helloworld1/AnyMemo#359]
"Conversion failed" when trying to "Import Q/A TXT" made as it says here
http://anymemo.org/wiki/index.php?title=Import/export
 "import tab separated TXT" works
Example in UTF-8:

"Q: 1
A: 2

Q: 1
A: 2" 

is smth wrong with this? Thank you.

If it is possible, please add import from regular office .xls as well.
txt import doesn't support "Enter" so lines are incredibly long and it is hard to edit them.
Thank you in advance.

**Comment by helloworld1** [comment]
Hi, In Excel, you can save your spreadsheet as .csv file. AnyMemo can directly import .csv file. AnyMemo will not support complex format like xls.
