### ISSUE TITLE
Card Player Promotion )

### ISSUE THREAD

**Issue by serheygmailcom** [helloworld1/AnyMemo#361]
It is really hard to overestimate "Card Player" as humans audio memory almost the same strong as visual. And fortunately it works great )
But maybe Card Player deserve a place in "Main option list" along with "Study" "Edit" "Card list" and "Quiz"...  and the same option to chose what to listen, at least "by range" (and maybe more - learning progress) as "Quiz" has it. Thank you )

**Comment by helloworld1** [comment]
Correct, the card player is kinda hidden there. More filtering options need to be added.

**Comment by helloworld1** [comment]
This issue was fixed with this commit. Thank you!
8f2e5c29c1b17536ef12266da4e50ffdc1e1eacc
