### ISSUE TITLE
Docs: Print Flashcards

### ISSUE THREAD

**Issue by guettli** [helloworld1/AnyMemo#373]
Please add some information how you can print (two sided) flashcards.

I could not find something here:

http://anymemo.org/wiki/index.php?title=Main_Page

**Comment by helloworld1** [comment]
I don't understand your request fully. If you want to display two sided cards, you can change the "Card style" to "Double sided" in the "Settings".

**Comment by guettli** [comment]
My use case is to print the flash cards on real world physical paper :-)

Or PDF export.

I guess printing two-sided is not that easy ...
