### ISSUE TITLE
Australian English text to speech support 

### ISSUE THREAD

**Issue by mosaic-greg** [helloworld1/AnyMemo#384]
Hi thank you for a terrific application. Now that Google has added Australian English text to speech support to Android, **is it possible to update AnyMemo to support this please**? Currently only US and UK English is supported. 

![eg](https://lh3.googleusercontent.com/4K1s_4mO_LGRdgdgAPtgg3yFb_ZlVR7Oc-L9xKYUb1QdlRBkrRza6a0goKPPCPxvDQ=h900)

**Comment by helloworld1** [comment]
I have added support for Australian English to the list.
I think for the Google's implementation, you need to set default language to Australian English to get it working. Let me know if you want to test the latest version.

**Comment by helloworld1** [comment]
https://github.com/helloworld1/AnyMemo/commit/501e5bbb6e02779fe02a6e85fab5ea07118c9b5f

**Comment by mosaic-greg** [comment]
Awesome thank you for the update. Yes I'd like to test the latest version,
is an apk available please?

**Comment by helloworld1** [comment]
I uploaded an APK here. It will replace the free version you have install. Please note, once you use this version, you will not be able to go back to older version because .db format.

https://drive.google.com/file/d/0B2Ipwyo9TOxYemoyT0V3MkdtUjg/view?usp=sharing

**Comment by mosaic-greg** [comment]
Wonderful it works great
