### ISSUE TITLE
The lower half of the file list browser of the database merger is masked.

### ISSUE THREAD

**Issue by ssakatausa** [helloworld1/AnyMemo#388]
In Anymemo, choose "Options", "Merge DB", and then tap the blank for "Target database". This brings up a browser screen. If you have enough number of databases in the directory, the databases in the second half of the screen are not shown.

**Comment by helloworld1** [comment]
Thank you for reporting the bug. I can reproduce the problem. It looks pretty bad. I will fix it soon!

**Comment by helloworld1** [comment]
Fixed the issue with the change below. I will release a new version soon.

commit e97376dc110dfab467da6f64e5119c6f1e0a1b69
Author: Howard Liberty <liberty@anymemo.org>
Date:   Wed Jun 1 18:20:00 2016 -0700

    Fix database merger's file browser UI not visible.
