### ISSUE TITLE
Firebase seems to be non-free

### ISSUE THREAD

**Issue by krt16s** [helloworld1/AnyMemo#389]
Firebase seems to be non-free software, could you replace it or make it non-mandatory?

**Comment by helloworld1** [comment]
I used Firebase client library for crash analytics and hope to make it public also. I would like to make it optional so it is not required for open sourced build. I haven't found a good way. Removing the google-services.json will result in build error.

**Comment by tomikmar** [comment]
I was looking for an updated AnyMemo version and I found that builds on F-Droid has been disabled:
* https://f-droid.org/wiki/page/org.liberty.android.fantastischmemo#10.9.1

Is there any chance for resolving this in the future?

**Comment by helloworld1** [comment]
I will remove firebase dependency as a resolution. It doesn't provide too much value right now.

**Comment by helloworld1** [comment]
Closing this issue. 98dc9b2adc0b06ed715dfa8383e081ae299c0d0e is checked in as a fix.

**Comment by helloworld1** [comment]
10.9.992 is released to play store (beta). All firebase references are removed.

**Comment by tomikmar** [comment]
Thank you. I created ticket to re-enable build on F-Droid:
* https://gitlab.com/fdroid/fdroiddata/issues/577

**Comment by helloworld1** [comment]
Google seems to be deprecating the current way of signing in Google account with WebView this month. Google Firebase auth would be the recommended way :( Don't know what I can do without using firebase dependency.

**Comment by tomikmar** [comment]
Maybe you could make Google-related features optional during compilation? Personally I don't need them. From my point of view having AnyMemo on F-Droid is more important.

**Comment by helloworld1** [comment]
Yes, I will try to work around the issue. It definitely makes authenticating Google drive harder for user.
