### ISSUE TITLE
Statistics for New Cards Learned each Day

### ISSUE THREAD

**Issue by xie-dongping** [helloworld1/AnyMemo#391]
As requested by #38 #84 , I wish to implement the statistics function for the number of new cards learned per day. After preliminary study, it seems to be only possible, when we add a column named `firstLearnDate`  to the `learning_data` table. 

I assumed that some changes are required for the following classes (maybe more):
```
entity.LearningData
dao.LearningDataDaoImpl
dao.CardDAO
ui.StatisticsScreen
``` 

So such feature would require automatically updating the old databases. But I could not find the place where I can put the upgrade code. The most suspicious one is the `AnyMemoDBOpenHelper.onCreate`, but it is not called when I open an old database.

As such, I was wondering if maybe you could tell me where you'd put the column insertion, or maybe you would have some smarter ways in mind for this feature.

**Comment by helloworld1** [comment]
The AnyMemoDBOpenHelper.onCreate was never explicitly called.
To open a db, call
AnyMemoDBOpenHelperManager.getHelper(Context, String filePath)

And release the db in onDestroy AnyMemoDBOpenHelperManager.releaseHelper(helper)

Once you call getHelper and have the AnyMemoDBOpenHelper instance, you can call getXXXDao for the DAO to actually interact with DB.

To add a column, you will need to 
1. change AnyMemoDBOpenHelper's onUpgrade to have a new version and add your columns with SQL.
        if (oldVersion <= 4) 
             {
             database.execSQL("alter table add column...");
}

Update CURRENT_VERSION to a newer version like "5".

This way, the database will update itself next time you launch the db in AnyMemo.

2. Change LearninData.java and add your column there. The column name is the database field name unless you specify it.
