### ISSUE TITLE
Add quick button or menu to bury/delete uninterested article from database during training.

### ISSUE THREAD

**Issue by gavenkoa** [helloworld1/AnyMemo#394]
During lesson I see cards that I don't like  and would like to delete from database. Anki software called that as **bury**.

It is inconvenient to enter to preview mode and search for these cards again. It would be better to have quick access button or menu entry during lesson to delete uninterested entries...

**Comment by helloworld1** [comment]
You can delete it by going to the menu (Press menu button or click on "..." on the top right) and select "Delete". Let me know if it helps.

**Comment by gavenkoa** [comment]
Hi. I didn't see "..." on the top right, only "magnifier sign".

But I didn't realize existence of menu on phone "Menu button". That solve my issue.

For clarification Anki software calls another feature as **Suspend Card** which *Hides a card or all of the note’s cards from review until they are manually unsuspended* not **Bury** as i wrote before. And AnyMemo has similar function called **Mark as forever learned**.

So I guess it is false issue, thanks for support!

**Comment by helloworld1** [comment]
No problem. Glad it works for you.
