### ISSUE TITLE
Do AnyMemo support colors in cards?

### ISSUE THREAD

**Issue by gavenkoa** [helloworld1/AnyMemo#398]
I made TAB file with HTML:

<b>America</b> [əˈmerɪkə]	<i style="color: green;">n</i><br><i style="color: blue;">ru</i> Америка<br><i style="color: blue;">uk</i> Америка<br>

`b` and `i` HTML tags have effect but `style="color: green;"` is not...

Also colors does not changed if import TAB file with `style="color: #00ff00;"`

Do AnyMemo support colors in cards?

**Comment by helloworld1** [comment]
The supported format tag is:

<font color="green">hello</font>
