### ISSUE TITLE
Update Icons to Flat Design

### ISSUE THREAD

**Issue by xie-dongping** [helloworld1/AnyMemo#399]
To follow the Zeitgeist of flat ui design, it might be good if Anymemo can update its internal icons to standard free (as in free speech) ones from [material design](https://design.google.com/icons/) or [Awesome fonts](http://fontawesome.io/icons/). 

As an engineer, I can only select the proper ones and maybe combine some icons. But it seem to be easy to find them. 

If you think it is alright, I'll start investigating and we can do a couple of iteration to see if my choices are ok.

**Comment by xie-dongping** [comment]
And it is then possible to create high dpi version of the icons, and it is a step towards material deisgn.

**Comment by helloworld1** [comment]
Yes, all icons should use material design. Currently, most icons are from Gnome, which are open sourced (CC) but not suitable for material design. I am OK with finding a new set of icons.

For High DPI icons, I think we should use vector icons instead if we are able to find.

https://materialdesignicons.com/ is also a good source of vector icons.

**Comment by xie-dongping** [comment]
I guess changing totally to VectorDrawable wouldn't be a bad idea, as it is already supported in support library v7, and in the worst case one can still use the rasterized version of the icons. I'm all for it, what do you think?

**Comment by helloworld1** [comment]
Yes, support library has already supported vector icons. I think vector icons is also good for the APK size too. AnyMemo should move to vector drawables.
