### ISSUE TITLE
Detailed Button for Items in the Recent List View

### ISSUE THREAD

**Issue by xie-dongping** [helloworld1/AnyMemo#406]
The context menu for items in the recent tab is only accessible through long pressing. 

If you think it is OK, I'll add a "details" button at the end of each item.

**Comment by xie-dongping** [comment]
What do you think about this? The context menu now for recent items is not really explicit.

**Comment by helloworld1** [comment]
That is a good idea. We probably need to add a overflow ("...") icon at the right most for each entry so the user can open the context menu.
