### ISSUE TITLE
More Functions in the Navigation Drawer (Options, About, Import)

### ISSUE THREAD

**Issue by xie-dongping** [helloworld1/AnyMemo#407]
It is somewhat common to have more buttons at the navigation drawer. 

I suppose that it would be nice to have the following functions directly accessible at the navigation drawer:

* Import
* Export
* Donate
* Options

What do you think?

**Comment by helloworld1** [comment]
More functions in drawer is good. I think Import / export are too much for drawer. We can have "Options", "About" in the drawer.

**Comment by xie-dongping** [comment]
I added the both buttons, the question is, if we want to remove the tab layout and use only the navigation drawer. If so, we could split the miscalleneous tab to import/export and option tab. 

I also got the feeling that both the file browser and download could actually be a action button for the recent tab (in that case, the home page). 

And the misc tab icon is really hard to decide. Other than the one I used, I think the following might be suitable. 

https://materialdesignicons.com/icon/puzzle
https://materialdesignicons.com/icon/collage
https://materialdesignicons.com/icon/tune-vertical
https://materialdesignicons.com/icon/multiplication-box

**Comment by helloworld1** [comment]
We can try the multiplication-box icon here. If it is not good, we can use puzzle. 
4 tabs is probably the max we can have in the list. I kinda agree recent tab and open tab serves similar approach, we can somehow merge those two. I don't have a clear idea in my head for the UI. It looks like a bad design to add action button in the same row as title "AnyMemo" row. Maybe a expandable floating action button would work here. Click "+" for expanding option to open in file browser, download or create an empty file. (Similar experience to Google Inbox)
