### ISSUE TITLE
Presenting the most recent card 'not remembered' again right after it was marked that way

### ISSUE THREAD

**Issue by TonyRamirezz** [helloworld1/AnyMemo#432]
This has been the single most annoying feature since I have been using AnyMemo. You mark a card not remembered and then it is presented to you again in the next card. Obviously nobody wants to review a card immediately after they have just seen it. Please change the randomization algorithm so that _at least_ one other card is displayed before the most recent not remembered card. (obviously there has to be an exception if there is only one card left in the queue!)

When I am learning, sometimes I will mark a difficult card as not remembered, even if can remember it. I do this when I believe I can remember the card for a few minutes but will not remember it the next day. This forces the card to reappear multiple times in the same learning session and it provides a way to intensively drill a particular card I want to learn quickly. I suspect other people do this as well. When the card reappears immediately, it frustrates this type of intense learning also.

**Comment by helloworld1** [comment]
Emmm, AnyMemo should not present you a failed card immediately. It will put the card to the end of learning queue and mix it with other failed cards and new cards. Could you tell me what is your settings in customize scheduling algorithms around queue size and review ordering? Have you changed it?

**Comment by TonyRamirezz** [comment]
Thanks for the quick reply

Don't remember if I ever changed these settings (would have been years ago if I did)
- queue size, 5
- review ordering, random

**Comment by helloworld1** [comment]
The default queue size it's 10. Ordering is hardest first. You can try to change those settings to see if it works for you.
