### ISSUE TITLE
[question] Switch question and answer

### ISSUE THREAD

**Issue by MartyIX** [helloworld1/AnyMemo#435]
Hi,

I have a deck with German -> English words. Can I set a settings to switch questions and answers? I mean when I see a German word I know what it is but I need to learn to answer the correct German word when I see an English one.

Thank you for the great app :-)

Regards
Martin

**Comment by helloworld1** [comment]
Yes, you can. First go to "Preview/edit" by long clicking a db file. And go to the dropdown menu through "..." and select "Advanced ..." and select "Swap the Q/A of all cards". You can swap all the question / answer. You also have the option to add all swapped card at the back so the total number of card will be doubles.

Back up your db file before this operation.  You cannot undo the swapping operation. You  can back up the db file in the second tab  (open tab) in the main screen by long clicking a db file and select "clone".
