### ISSUE TITLE
GoogleDrive support requires non-free deps

### ISSUE THREAD

**Issue by ghost** [helloworld1/AnyMemo#436]
GoodleDrive support requires non-free dependencies (play-services), but ended up being added to the generic build instead of prod/dev flavors. This breaks the free build flavor.

Ref: https://github.com/helloworld1/AnyMemo/commit/cae1cbac4889055f358de159698a429c32201a77

**Comment by helloworld1** [comment]
I definitely need help on this. I have been trying for weeks to use web API to access GDrive but Google forbids this way of access. Also microG doesn't work well either. To get a timely release on Google Play, I have to include google play sdk for now :-1: 

I am thinking about idea to shim away the google play and create a openSouced variant of the app to not include non-free SDKs. But I don't have enough time to do that. 
If you have any quick way to make f-droid build again, please let me know.

**Comment by tomikmar** [comment]
I've been using AnyMemo for years and I've never needed Google integration. In my opinion free variant without Google would be a good idea.

**Comment by helloworld1** [comment]
It is unfortunate decoupling the Google Play Services is very challenging and Google has been increasing making tight integration of play services and Android development.

For the time being, please use IzzyOnDroid repo on F-droid to access the app with the caveat of "NonFreeDep":
https://apt.izzysoft.de/fdroid/index/apk/org.liberty.android.fantastischmemo
