### ISSUE TITLE
Pressing Paint in Quiz mode crashes the app every time

### ISSUE THREAD

**Issue by antonv6** [helloworld1/AnyMemo#440]
No idea why, but it happens every time:

- tap More on any database (e.g. french-body-parts.db)
- select Quiz
- select some cards and press Start
- select Paint in menu
- crash

Paint works fine from Study mode (although I didn't see any way to clear the screen). App version: 10.10.1.

**Comment by helloworld1** [comment]
Thank you for reporting the bug. I am able to reproduce the crash. I will fix it. 
There is a way to clear the screen, you can click the right of the top bar. There is a hidden tap target on the upper right of the screen. It must be a bug with the icon. I will also fix it.

**Comment by helloworld1** [comment]
The paint crash was fixed in commit e328ca8ffc7c8d076544208116795b3c98f6d4b1 and dfb95080eaaf67055c9e5182be3e99260a56eaab
