### ISSUE TITLE
請問有人知怎樣用疑問音調讀有問號的問題句嗎??????????

### ISSUE THREAD

**Issue by yl8883** [helloworld1/AnyMemo#446]
英文是懂用疑問音調讀問題型式的句子的,但日文及韓文則對問號不起作用了,問問題讀成與一般陳述句一樣,最尾的字一成不變,是否在card上打些什麼字符可以使多音字自動選讀另一個指定的音呢?

**Comment by helloworld1** [comment]
This is handled by your Text-to-speech engine. If your text-to-speech engine do not how to handle the question mark correctly, you probably want to use another engine.

BTW, have you tried using both half width and full width question mark? Maybe your engine only recognize on of them. 

There is unfortunately nothing AnyMemo can help this in code.
