### ISSUE TITLE
Where can I find the Windows 'db builder' utility?

### ISSUE THREAD

**Issue by TonyRamirezz** [helloworld1/AnyMemo#447]
I searched long and hard but kind find any reference to it on the web or the official site which is weird. Can't remember what it's called because the laptop I used it on has died. It's the program that will import a formatted text file and spit out a .db file.

**Comment by helloworld1** [comment]
The windows app is deprecated and removed. You can copy the text file to your phone and use the "Import" function in AnyMemo app.
