### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [helloworld1/AnyMemo#453]
After a double rotation of the ui.AnyMemo there is in heap memory 1 instance more of:

class org.liberty.android.fantastischmemo.ui.RecentListFragment @ 0x12ddc000
class org.liberty.android.fantastischmemo.ui.OpenTabFragment @ 0x12de0400

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onCreate-onDestroy lifecycle.

**Comment by helloworld1** [comment]
After this commit 3c48a1a3e726545a4ef2e05d3c44801a483daad7, AnyMemo has moved to bottom nav and should avoid the view pager fragment leak.
