### ISSUE TITLE
Cannot rename database

### ISSUE THREAD

**Issue by gaul** [helloworld1/AnyMemo#467]
I have created a database by merging several smaller ones and the original name no longer makes sense.

**Comment by helloworld1** [comment]
You can rename the database in the "Open" tab in the main screen. Long click a db file and select "Rename". You can rename it by changing the file name in the last part of the path. If you change the path, it will actually move the file.

**Comment by gaul** [comment]
I see, long press in the open tab has this feature but recent tab does not.
