### ISSUE TITLE
Cannot edit card from card list

### ISSUE THREAD

**Issue by gaul** [helloworld1/AnyMemo#475]
When browsing through the card list I noticed a typo.  I could not edit from this activity and had to cycle through all the cards to find the typo.  The long click dialog should include an option to edit:

![2019-04-26 10 06 59](https://user-images.githubusercontent.com/848247/56792360-6ef31500-6844-11e9-941b-cbc90e536753.png)

**Comment by helloworld1** [comment]
I think you can long click on a row and select "Edit" to edit that card. Let me know if it works.

**Comment by gaul** [comment]
My mistake; the above screenshot is from a short click.  A long click displays edit, detail, and preview as you suggest.
