### ISSUE TITLE
NullPointerException: Unable to start FileBrowserActivity

### ISSUE THREAD

**Issue by anlalalu** [helloworld1/AnyMemo#489]
###### Reproduction Steps
This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am start -n org.liberty.android.fantastischmemo/org.liberty.android.fantastischmemo.ui.FileBrowserActivity

###### Stack Trace

E/AndroidRuntime( 5134): FATAL EXCEPTION: main
E/AndroidRuntime( 5134): Process: org.liberty.android.fantastischmemo, PID: 5134
E/AndroidRuntime( 5134): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.liberty.android.fantastischmemo/org.liberty.android.fantastischmemo.ui.FileBrowserActivity}: java.lang.NullPointerException
E/AndroidRuntime( 5134): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 5134): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 5134): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 5134): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 5134): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5134): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5134): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 5134): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5134): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5134): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5134): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5134): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5134): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 5134): 	at org.liberty.android.fantastischmemo.ui.FileBrowserActivity.onCreate(FileBrowserActivity.java:43)
E/AndroidRuntime( 5134): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 5134): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 5134): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 5134): 	... 11 more

###### Debug info
App Version = 10.11.3

Android Version = 7.1.0

**Comment by helloworld1** [comment]
FileBrowserActivity  is not intended to open without argument.
