### ISSUE TITLE
the category information lost if editing a card and back to the learning screen

### ISSUE THREAD

**Issue by tingsu** [helloworld1/AnyMemo#495]
Hi @helloworld1 , thanks for maintaining this app!

I observed a small GUI issue in the latest released version v10.11.4 on an Android 6.0 device. The category information will be temporarily lost if I edit a card and go back to the learning screen.  I searched the history issue, and found this issue has not been noticed before.  Hope this issue could be fixed, that will be nice :) 

Reproducing video:

- Note the original info is ``Today: 0 New: 28 Rev: 0 ID: 1 C: French (Body parts)``, but after the editing (in fact, I did nothing, just click the ``save`` button), the info becomes ``Today: 0 New: 28 Rev: 0 ID: 1``. 

- I also tried on other dictionaries with category info. The same issue appear.

![20200416_175425](https://user-images.githubusercontent.com/3156978/79478382-a0dc2900-800b-11ea-8fda-dc89cf2f2f08.gif)

**Comment by helloworld1** [comment]
There is actually a fix there in pull request. It has performance impact. But it can make data consistent.

**Comment by tingsu** [comment]
@helloworld1 , thanks for your responsive reply and confirmation. I found the pull request #478 on this issue.

**Comment by helloworld1** [comment]
It is merged after 10.11.4. So it does not land in the released version:
https://github.com/helloworld1/AnyMemo/pull/478

**Comment by tingsu** [comment]
Got it. Thanks, @helloworld1 .

**Comment by tingsu** [comment]
Hi @helloworld1, considering the PR #478 was already merged into the latest master, can I close this issue?
