### ISSUE TITLE
Web page refresh after rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [helloworld1/AnyMemo#499]
Steps to reproduce:
1. click download tab
2. click Quizlet
3. click private cards
4. Click any links in the web page, such as sign up
5. rotate screen

The content in web page should still be there, however, it refresh to the initial web page

![Screen Shot 2020-08-05 at 7 52 19 PM](https://user-images.githubusercontent.com/67744580/89410126-bfe6fe00-d755-11ea-8cb8-8e8575db19d8.png)
![Screen Shot 2020-08-05 at 7 52 29 PM](https://user-images.githubusercontent.com/67744580/89410132-c1b0c180-d755-11ea-876a-07e8e4e546ca.png)

**Comment by helloworld1** [comment]
Quizlet was removed in the latest build since Quizlet does not allow third party to use their API anymore. They only allow their own app to use.
