### ISSUE TITLE
Question about some XML files

### ISSUE THREAD

**Issue by neves01** [helloworld1/AnyMemo#506]
Hello guys,

I'm studying and testing the AnyMemo app. Anyone know if the project has inactive xml files (from layout folder)?

Some I saw in the project:
- flashcard_screen.xml
- filter_dialog.xml
- drawer_list_item.xml
- oauth_login_layout.xml
- quizlet_launcher.xml

Thanks in advance.

**Comment by helloworld1** [comment]
Yes, I think some of the XMLs were previously deleted screens but not cleaned up.
